# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 999
    ignore:
      - dependency-name: 'step-security/harden-runner'
        versions: '>= 2'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 999
    groups:
      cloudflare:
        patterns:
          - '@cloudflare/*'
          - 'wrangler'
        exclude-patterns:
          - '@cloudflare/workers-types'
      typescript:
        patterns:
          - '@types/*'
          - '@cloudflare/workers-types'
          - 'ts-node'
          - 'typescript'
      code-management:
        patterns:
          - 'prettier'
          - '@demosjarco/prettier-config'
          - 'eslint'
